display_name="WellySmash Ultimate TE"
authors = "JoBen modified by sharlot"
description="""
Created by JoBen

Are you a tournament player that only plays on legal stages and is annoyed by how hard it is to navigate or see where the stages are? 
This mod is just right for you!

Ultimate TE is a Smash Ultimate UI mod that aims to be more suited for Competitive players! 

Modified for WellySmash by sharlot 
"""
version="1.2"
category="UI"